---
driver_plugin: docker
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu
  driver_config:
    image: inokappa/ubuntu
    socket: tcp://127.0.0.1:4243

suites:
- name: default
  run_list: [
    "recipe[htpasswd]",
    "recipe[nagios-nagira_cookbook::apt_update]",
    "recipe[nagios-nagira_cookbook::app_install]",
]
  attributes: {}

busser:
  sudo: true
