---
driver_plugin: docker
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu
  driver_config:
    image: inokappa/wheezy-7.2-basic
    socket: tcp://172.16.80.70:4243

suites:
- name: default
  run_list: [
    "recipe[nagios-nagira_cookbook::apt_update]",
    "recipe[nagios-nagira_cookbook::app_install]",
]
  attributes: {}

busser:
  sudo: true
